Avoid unused-variable warning on Windows
When compiling with clang-cl:

.../ir_emit.c(275,8): error: unused variable 'handle' [-Werror,-Wunused-variable]
  275 |         void *handle = NULL;
      |               ^~~~~~